# Use a base img
FROM python:3.12-slim

# Set the working dir in the container
WORKDIR /app

# Copy and install dependencies
COPY . /app
RUN pip install --no-cache-dir -r preprocessing_requirements.txt

# Copy app code and data
COPY . .

# Expose port
EXPOSE 80

CMD ["python", "inference.py"]