apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-app
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: inference-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1  
      maxUnavailable: 0  
  template:
    metadata:
      labels:
        app: inference-app
    spec:
      containers:
      - name: inference-container
        image: alyssa8008/inference-service:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: model-volume
          mountPath: /model
      volumes: 
      - name: model-volume
        persistentVolumeClaim:
          claimName: model-pvc           
---
apiVersion: v1
kind: Service
metadata:
  name: inference-service
spec:
  selector:
    app: inference-app
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 80
  type: ClusterIP

